language: node_js
node_js: lts/carbon

cache:
  directories:
    - node_modules

install: npm install

services:
  - redis-server

script:
  - npm run tslint
  - npm test

env:
  global:
    - REDISCLOUD_URL=redis://127.0.0.1
    - secure: "p+Ds4uL18bAhVAf81YO9IY3azsJkM44/8UcLw7ATroAwxbfjoyipZjS9znPzMd9mWxl3NfFSLAqAcICHvKGEaV3W7898LvidFQ9g8YltlzeuLrId3hf0JbXZEw+DsubFZkZHFWkoNncPow6fEGcqySvoXbsZeQRR+9/juhhitx2GlQMXqcYvq0D8ZoC7WgSpC8ABVAiRH/HLRL1EEzY4IVUw2YLFQ8bzBDy4MfjUdwc01ceT19RouguXsu8umUE1pOhFh7C/SQwQayhQousg6dVDZUvRu/e8Ca3PSl5UiBp4IzXTY0xjWCYwX4sbZLFcDHKLGBSU/HOgVNe76tHxSXHQ/i8UEJQzgjvNq37UulMN7HjtB8L/shDNFtOd0VIkaInrNuSBB5BxUwtJk2isP8DbLIJ/LSAiyl2TM8gTTd6pPG9G48x76W7MQTel+vm43K6HRDeGiXl8yflqyt6QG6tfgWbr8Yr4BU80yB4nKp8envJlZ2yxGk7tUb6bCqT3bJfrO6WubzV/fWIrZbL8P7ezo+IfwKBsDeqgtgO/KYTbUpEHXI8om+954wy93y0KH0x+F/G1Z01IsvZPs2p7+l9XEDGi0mP1BAW763mLzhKUytJ0R6CBnNArCSMGfH3NhOOyQ0BgfJWvQUY8D4wmWaPRYaPx77mxWx5swHi8oeE="

before_cache: rm -rf node_modules/.cache

after_success: cat ./coverage/lcov.info | coveralls
before_script:
  - if [ $GH_TOKEN ]; then greenkeeper-lockfile-update; fi;
after_script:
  - if [ $GH_TOKEN ]; then greenkeeper-lockfile-upload; fi;
